"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProxyStandardStorageSlot__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        name: "Advance",
        type: "event",
        inputs: [
            {
                name: "epoch",
                type: "uint256",
                indexed: true,
                internalType: "uint256",
            },
            {
                name: "block",
                type: "uint256",
                indexed: false,
                internalType: "uint256",
            },
            {
                name: "timestamp",
                type: "uint256",
                indexed: false,
                internalType: "uint256",
            },
        ],
        anonymous: false,
    },
    {
        name: "Bond",
        type: "event",
        inputs: [
            {
                name: "account",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "start",
                type: "uint256",
                indexed: false,
                internalType: "uint256",
            },
            {
                name: "value",
                type: "uint256",
                indexed: false,
                internalType: "uint256",
            },
            {
                name: "valueUnderlying",
                type: "uint256",
                indexed: false,
                internalType: "uint256",
            },
        ],
        anonymous: false,
    },
    {
        name: "Commit",
        type: "event",
        inputs: [
            {
                name: "account",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "candidate",
                type: "address",
                indexed: true,
                internalType: "address",
            },
        ],
        anonymous: false,
    },
    {
        name: "CouponApproval",
        type: "event",
        inputs: [
            {
                name: "owner",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "spender",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "value",
                type: "uint256",
                indexed: false,
                internalType: "uint256",
            },
        ],
        anonymous: false,
    },
    {
        name: "CouponExpiration",
        type: "event",
        inputs: [
            {
                name: "epoch",
                type: "uint256",
                indexed: true,
                internalType: "uint256",
            },
            {
                name: "couponsExpired",
                type: "uint256",
                indexed: false,
                internalType: "uint256",
            },
            {
                name: "lessRedeemable",
                type: "uint256",
                indexed: false,
                internalType: "uint256",
            },
            {
                name: "lessDebt",
                type: "uint256",
                indexed: false,
                internalType: "uint256",
            },
            {
                name: "newBonded",
                type: "uint256",
                indexed: false,
                internalType: "uint256",
            },
        ],
        anonymous: false,
    },
    {
        name: "CouponPurchase",
        type: "event",
        inputs: [
            {
                name: "account",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "epoch",
                type: "uint256",
                indexed: true,
                internalType: "uint256",
            },
            {
                name: "dollarAmount",
                type: "uint256",
                indexed: false,
                internalType: "uint256",
            },
            {
                name: "couponAmount",
                type: "uint256",
                indexed: false,
                internalType: "uint256",
            },
        ],
        anonymous: false,
    },
    {
        name: "CouponRedemption",
        type: "event",
        inputs: [
            {
                name: "account",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "epoch",
                type: "uint256",
                indexed: true,
                internalType: "uint256",
            },
            {
                name: "couponAmount",
                type: "uint256",
                indexed: false,
                internalType: "uint256",
            },
        ],
        anonymous: false,
    },
    {
        name: "CouponTransfer",
        type: "event",
        inputs: [
            {
                name: "from",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "to",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "epoch",
                type: "uint256",
                indexed: true,
                internalType: "uint256",
            },
            {
                name: "value",
                type: "uint256",
                indexed: false,
                internalType: "uint256",
            },
        ],
        anonymous: false,
    },
    {
        name: "Deposit",
        type: "event",
        inputs: [
            {
                name: "account",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "value",
                type: "uint256",
                indexed: false,
                internalType: "uint256",
            },
        ],
        anonymous: false,
    },
    {
        name: "Incentivization",
        type: "event",
        inputs: [
            {
                name: "account",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "amount",
                type: "uint256",
                indexed: false,
                internalType: "uint256",
            },
        ],
        anonymous: false,
    },
    {
        name: "Proposal",
        type: "event",
        inputs: [
            {
                name: "candidate",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "account",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "start",
                type: "uint256",
                indexed: true,
                internalType: "uint256",
            },
            {
                name: "period",
                type: "uint256",
                indexed: false,
                internalType: "uint256",
            },
        ],
        anonymous: false,
    },
    {
        name: "SupplyDecrease",
        type: "event",
        inputs: [
            {
                name: "epoch",
                type: "uint256",
                indexed: true,
                internalType: "uint256",
            },
            {
                name: "price",
                type: "uint256",
                indexed: false,
                internalType: "uint256",
            },
            {
                name: "newDebt",
                type: "uint256",
                indexed: false,
                internalType: "uint256",
            },
        ],
        anonymous: false,
    },
    {
        name: "SupplyIncrease",
        type: "event",
        inputs: [
            {
                name: "epoch",
                type: "uint256",
                indexed: true,
                internalType: "uint256",
            },
            {
                name: "price",
                type: "uint256",
                indexed: false,
                internalType: "uint256",
            },
            {
                name: "newRedeemable",
                type: "uint256",
                indexed: false,
                internalType: "uint256",
            },
            {
                name: "lessDebt",
                type: "uint256",
                indexed: false,
                internalType: "uint256",
            },
            {
                name: "newBonded",
                type: "uint256",
                indexed: false,
                internalType: "uint256",
            },
        ],
        anonymous: false,
    },
    {
        name: "SupplyNeutral",
        type: "event",
        inputs: [
            {
                name: "epoch",
                type: "uint256",
                indexed: true,
                internalType: "uint256",
            },
        ],
        anonymous: false,
    },
    {
        name: "Transfer",
        type: "event",
        inputs: [
            {
                name: "from",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "to",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "value",
                type: "uint256",
                indexed: false,
                internalType: "uint256",
            },
        ],
        anonymous: false,
    },
    {
        name: "Unbond",
        type: "event",
        inputs: [
            {
                name: "account",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "start",
                type: "uint256",
                indexed: false,
                internalType: "uint256",
            },
            {
                name: "value",
                type: "uint256",
                indexed: false,
                internalType: "uint256",
            },
            {
                name: "valueUnderlying",
                type: "uint256",
                indexed: false,
                internalType: "uint256",
            },
        ],
        anonymous: false,
    },
    {
        name: "Upgraded",
        type: "event",
        inputs: [
            {
                name: "implementation",
                type: "address",
                indexed: true,
                internalType: "address",
            },
        ],
        anonymous: false,
    },
    {
        name: "Vote",
        type: "event",
        inputs: [
            {
                name: "account",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "candidate",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "vote",
                type: "uint8",
                indexed: false,
                internalType: "enum Candidate.Vote",
            },
            {
                name: "bonded",
                type: "uint256",
                indexed: false,
                internalType: "uint256",
            },
        ],
        anonymous: false,
    },
    {
        name: "Withdraw",
        type: "event",
        inputs: [
            {
                name: "account",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "value",
                type: "uint256",
                indexed: false,
                internalType: "uint256",
            },
        ],
        anonymous: false,
    },
    {
        name: "advance",
        type: "function",
        inputs: [],
        outputs: [],
        payable: false,
        constant: false,
        stateMutability: "nonpayable",
    },
    {
        name: "allowance",
        type: "function",
        inputs: [
            {
                name: "owner",
                type: "address",
                internalType: "address",
            },
            {
                name: "spender",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [
            {
                name: "",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        payable: false,
        constant: true,
        stateMutability: "view",
    },
    {
        name: "allowanceCoupons",
        type: "function",
        inputs: [
            {
                name: "owner",
                type: "address",
                internalType: "address",
            },
            {
                name: "spender",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [
            {
                name: "",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        payable: false,
        constant: true,
        stateMutability: "view",
    },
    {
        name: "approve",
        type: "function",
        inputs: [
            {
                name: "spender",
                type: "address",
                internalType: "address",
            },
            {
                name: "amount",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        outputs: [
            {
                name: "",
                type: "bool",
                internalType: "bool",
            },
        ],
        payable: false,
        constant: false,
        stateMutability: "nonpayable",
    },
    {
        name: "approveCoupons",
        type: "function",
        inputs: [
            {
                name: "spender",
                type: "address",
                internalType: "address",
            },
            {
                name: "amount",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        outputs: [],
        payable: false,
        constant: false,
        stateMutability: "nonpayable",
    },
    {
        name: "approveFor",
        type: "function",
        inputs: [
            {
                name: "candidate",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [
            {
                name: "",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        payable: false,
        constant: true,
        stateMutability: "view",
    },
    {
        name: "balanceOf",
        type: "function",
        inputs: [
            {
                name: "account",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [
            {
                name: "",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        payable: false,
        constant: true,
        stateMutability: "view",
    },
    {
        name: "balanceOfBonded",
        type: "function",
        inputs: [
            {
                name: "account",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [
            {
                name: "",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        payable: false,
        constant: true,
        stateMutability: "view",
    },
    {
        name: "balanceOfCoupons",
        type: "function",
        inputs: [
            {
                name: "account",
                type: "address",
                internalType: "address",
            },
            {
                name: "epoch",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        outputs: [
            {
                name: "",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        payable: false,
        constant: true,
        stateMutability: "view",
    },
    {
        name: "balanceOfStaged",
        type: "function",
        inputs: [
            {
                name: "account",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [
            {
                name: "",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        payable: false,
        constant: true,
        stateMutability: "view",
    },
    {
        name: "bond",
        type: "function",
        inputs: [
            {
                name: "value",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        outputs: [],
        payable: false,
        constant: false,
        stateMutability: "nonpayable",
    },
    {
        name: "bootstrappingAt",
        type: "function",
        inputs: [
            {
                name: "epoch",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        outputs: [
            {
                name: "",
                type: "bool",
                internalType: "bool",
            },
        ],
        payable: false,
        constant: true,
        stateMutability: "view",
    },
    {
        name: "calculatePrice",
        type: "function",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        payable: false,
        constant: true,
        stateMutability: "view",
    },
    {
        name: "calculateReward",
        type: "function",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        payable: false,
        constant: true,
        stateMutability: "view",
    },
    {
        name: "commit",
        type: "function",
        inputs: [
            {
                name: "candidate",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [],
        payable: false,
        constant: false,
        stateMutability: "nonpayable",
    },
    {
        name: "couponPremium",
        type: "function",
        inputs: [
            {
                name: "amount",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        outputs: [
            {
                name: "",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        payable: false,
        constant: true,
        stateMutability: "view",
    },
    {
        name: "couponsExpiration",
        type: "function",
        inputs: [
            {
                name: "epoch",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        outputs: [
            {
                name: "",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        payable: false,
        constant: true,
        stateMutability: "view",
    },
    {
        name: "decimals",
        type: "function",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "uint8",
                internalType: "uint8",
            },
        ],
        payable: false,
        constant: true,
        stateMutability: "view",
    },
    {
        name: "deposit",
        type: "function",
        inputs: [
            {
                name: "value",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        outputs: [],
        payable: false,
        constant: false,
        stateMutability: "nonpayable",
    },
    {
        name: "dollar",
        type: "function",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "address",
                internalType: "contract IDollar",
            },
        ],
        payable: false,
        constant: true,
        stateMutability: "view",
    },
    {
        name: "emergencyCommit",
        type: "function",
        inputs: [
            {
                name: "candidate",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [],
        payable: false,
        constant: false,
        stateMutability: "nonpayable",
    },
    {
        name: "epoch",
        type: "function",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        payable: false,
        constant: true,
        stateMutability: "view",
    },
    {
        name: "epochTime",
        type: "function",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        payable: false,
        constant: true,
        stateMutability: "view",
    },
    {
        name: "expiringCoupons",
        type: "function",
        inputs: [
            {
                name: "epoch",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        outputs: [
            {
                name: "",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        payable: false,
        constant: true,
        stateMutability: "view",
    },
    {
        name: "expiringCouponsAtIndex",
        type: "function",
        inputs: [
            {
                name: "epoch",
                type: "uint256",
                internalType: "uint256",
            },
            {
                name: "i",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        outputs: [
            {
                name: "",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        payable: false,
        constant: true,
        stateMutability: "view",
    },
    {
        name: "fluidUntil",
        type: "function",
        inputs: [
            {
                name: "account",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [
            {
                name: "",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        payable: false,
        constant: true,
        stateMutability: "view",
    },
    {
        name: "implementation",
        type: "function",
        inputs: [],
        outputs: [
            {
                name: "impl",
                type: "address",
                internalType: "address",
            },
        ],
        payable: false,
        constant: true,
        stateMutability: "view",
    },
    {
        name: "initialize",
        type: "function",
        inputs: [],
        outputs: [],
        payable: false,
        constant: false,
        stateMutability: "nonpayable",
    },
    {
        name: "isInitialized",
        type: "function",
        inputs: [
            {
                name: "candidate",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [
            {
                name: "",
                type: "bool",
                internalType: "bool",
            },
        ],
        payable: false,
        constant: true,
        stateMutability: "view",
    },
    {
        name: "isNominated",
        type: "function",
        inputs: [
            {
                name: "candidate",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [
            {
                name: "",
                type: "bool",
                internalType: "bool",
            },
        ],
        payable: false,
        constant: true,
        stateMutability: "view",
    },
    {
        name: "lockedUntil",
        type: "function",
        inputs: [
            {
                name: "account",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [
            {
                name: "",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        payable: false,
        constant: true,
        stateMutability: "view",
    },
    {
        name: "name",
        type: "function",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "string",
                internalType: "string",
            },
        ],
        payable: false,
        constant: true,
        stateMutability: "view",
    },
    {
        name: "oracle",
        type: "function",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "address",
                internalType: "contract IOracle",
            },
        ],
        payable: false,
        constant: true,
        stateMutability: "view",
    },
    {
        name: "outstandingCoupons",
        type: "function",
        inputs: [
            {
                name: "epoch",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        outputs: [
            {
                name: "",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        payable: false,
        constant: true,
        stateMutability: "view",
    },
    {
        name: "periodFor",
        type: "function",
        inputs: [
            {
                name: "candidate",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [
            {
                name: "",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        payable: false,
        constant: true,
        stateMutability: "view",
    },
    {
        name: "pool",
        type: "function",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "address",
                internalType: "address",
            },
        ],
        payable: false,
        constant: true,
        stateMutability: "view",
    },
    {
        name: "purchaseCoupons",
        type: "function",
        inputs: [
            {
                name: "dollarAmount",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        outputs: [
            {
                name: "",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        payable: false,
        constant: false,
        stateMutability: "nonpayable",
    },
    {
        name: "recordedVote",
        type: "function",
        inputs: [
            {
                name: "account",
                type: "address",
                internalType: "address",
            },
            {
                name: "candidate",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [
            {
                name: "",
                type: "uint8",
                internalType: "enum Candidate.Vote",
            },
        ],
        payable: false,
        constant: true,
        stateMutability: "view",
    },
    {
        name: "redeemCoupons",
        type: "function",
        inputs: [
            {
                name: "couponEpoch",
                type: "uint256",
                internalType: "uint256",
            },
            {
                name: "couponAmount",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        outputs: [],
        payable: false,
        constant: false,
        stateMutability: "nonpayable",
    },
    {
        name: "rejectFor",
        type: "function",
        inputs: [
            {
                name: "candidate",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [
            {
                name: "",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        payable: false,
        constant: true,
        stateMutability: "view",
    },
    {
        name: "startFor",
        type: "function",
        inputs: [
            {
                name: "candidate",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [
            {
                name: "",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        payable: false,
        constant: true,
        stateMutability: "view",
    },
    {
        name: "statusOf",
        type: "function",
        inputs: [
            {
                name: "account",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [
            {
                name: "",
                type: "uint8",
                internalType: "enum Account.Status",
            },
        ],
        payable: false,
        constant: true,
        stateMutability: "view",
    },
    {
        name: "symbol",
        type: "function",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "string",
                internalType: "string",
            },
        ],
        payable: false,
        constant: true,
        stateMutability: "view",
    },
    {
        name: "totalBonded",
        type: "function",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        payable: false,
        constant: true,
        stateMutability: "view",
    },
    {
        name: "totalBondedAt",
        type: "function",
        inputs: [
            {
                name: "epoch",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        outputs: [
            {
                name: "",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        payable: false,
        constant: true,
        stateMutability: "view",
    },
    {
        name: "totalCoupons",
        type: "function",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        payable: false,
        constant: true,
        stateMutability: "view",
    },
    {
        name: "totalDebt",
        type: "function",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        payable: false,
        constant: true,
        stateMutability: "view",
    },
    {
        name: "totalNet",
        type: "function",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        payable: false,
        constant: true,
        stateMutability: "view",
    },
    {
        name: "totalRedeemable",
        type: "function",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        payable: false,
        constant: true,
        stateMutability: "view",
    },
    {
        name: "totalStaged",
        type: "function",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        payable: false,
        constant: true,
        stateMutability: "view",
    },
    {
        name: "totalSupply",
        type: "function",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        payable: false,
        constant: true,
        stateMutability: "view",
    },
    {
        name: "transfer",
        type: "function",
        inputs: [
            {
                name: "recipient",
                type: "address",
                internalType: "address",
            },
            {
                name: "amount",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        outputs: [
            {
                name: "",
                type: "bool",
                internalType: "bool",
            },
        ],
        payable: false,
        constant: false,
        stateMutability: "nonpayable",
    },
    {
        name: "transferCoupons",
        type: "function",
        inputs: [
            {
                name: "sender",
                type: "address",
                internalType: "address",
            },
            {
                name: "recipient",
                type: "address",
                internalType: "address",
            },
            {
                name: "epoch",
                type: "uint256",
                internalType: "uint256",
            },
            {
                name: "amount",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        outputs: [],
        payable: false,
        constant: false,
        stateMutability: "nonpayable",
    },
    {
        name: "transferFrom",
        type: "function",
        inputs: [
            {
                name: "sender",
                type: "address",
                internalType: "address",
            },
            {
                name: "recipient",
                type: "address",
                internalType: "address",
            },
            {
                name: "amount",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        outputs: [
            {
                name: "",
                type: "bool",
                internalType: "bool",
            },
        ],
        payable: false,
        constant: false,
        stateMutability: "nonpayable",
    },
    {
        name: "unbond",
        type: "function",
        inputs: [
            {
                name: "value",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        outputs: [],
        payable: false,
        constant: false,
        stateMutability: "nonpayable",
    },
    {
        name: "unbondUnderlying",
        type: "function",
        inputs: [
            {
                name: "value",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        outputs: [],
        payable: false,
        constant: false,
        stateMutability: "nonpayable",
    },
    {
        name: "vote",
        type: "function",
        inputs: [
            {
                name: "candidate",
                type: "address",
                internalType: "address",
            },
            {
                name: "vote",
                type: "uint8",
                internalType: "enum Candidate.Vote",
            },
        ],
        outputs: [],
        payable: false,
        constant: false,
        stateMutability: "nonpayable",
    },
    {
        name: "votesFor",
        type: "function",
        inputs: [
            {
                name: "candidate",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [
            {
                name: "",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        payable: false,
        constant: true,
        stateMutability: "view",
    },
    {
        name: "withdraw",
        type: "function",
        inputs: [
            {
                name: "value",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        outputs: [],
        payable: false,
        constant: false,
        stateMutability: "nonpayable",
    },
];
class ProxyStandardStorageSlot__factory {
    static createInterface() {
        return new ethers_1.Interface(_abi);
    }
    static connect(address, runner) {
        return new ethers_1.Contract(address, _abi, runner);
    }
}
exports.ProxyStandardStorageSlot__factory = ProxyStandardStorageSlot__factory;
ProxyStandardStorageSlot__factory.abi = _abi;
